### ISSUE TITLE
The callback URL is either unknown or invalid

### ISSUE THREAD

**Issue by jlxq0** [simplificator/simplificator-withings#22]
Whatever URL I enter ... I always end up like this:

```
  irb(main):013:0> user.subscribe_notification('http://foo.bar.com', 'test subscription')
  Withings::ApiError: The callback URL 'http://foo.bar.com' is either unknown or invalid - Status code: 293
    from /app/vendor/bundle/ruby/2.2.0/gems/simplificator-withings-0.7.0/lib/withings/connection.rb:80:in `verify_response!'
    from /app/vendor/bundle/ruby/2.2.0/gems/simplificator-withings-0.7.0/lib/withings/connection.rb:22:in `get_request'
    from /app/vendor/bundle/ruby/2.2.0/gems/simplificator-withings-0.7.0/lib/withings/connection.rb:27:in `get_request'
    from /app/vendor/bundle/ruby/2.2.0/gems/simplificator-withings-0.7.0/lib/withings/user.rb:26:in `subscribe_notification'
    from (irb):13
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'
```

Anyone with similar problems or maybe a solution?

**Comment by jlxq0** [comment]
So I tried without the withings simplificator gem:

```
API_KEY       = '123'
API_SECRET    = '456'
USER_ID       = '789'
USER_KEY      = 'abc'
USER_SECRET   = 'def'
CONFIGURATION = {               site: 'https://oauth.withings.com',
                  request_token_path: '/account/request_token',
                   access_token_path: '/account/access_token',
                      authorize_path: '/account/authorize',
                         http_method: :get,
                              scheme: :query_string
                }

@consumer = OAuth::Consumer.new API_KEY, API_SECRET, CONFIGURATION

@access_token = OAuth::AccessToken.new @consumer, USER_KEY, USER_SECRET

url = ERB::Util.url_encode("www.foo.bar/trigger")
comment = ERB::Util.url_encode("Trigger")
response = @access_token.get("https://wbsapi.withings.net/notify?action=subscribe&userid=#{USER_ID}&callbackurl=#{url}&comment=#{comment}")
JSON.parse(response.body)
```

Still no luck :(

**Comment by pascalbetz** [comment]
Thanks for the report.
So it looks like this is a withings issue? Have you checked the docs? Any updates there?

**Comment by jlxq0** [comment]
It seems so, yes. I checked the docs and also created a question on stackoverflow: http://stackoverflow.com/questions/32705208/withings-api-the-callback-url-is-either-unknown-or-invalid
No luck until now. Does subscribing work for you, @pascalbetz? Anythings else with the API works just fine for me.

**Comment by pascalbetz** [comment]
I am currently not using Withings. But from my experience working on the Gem this has happened before: APIs changed or were badly documented. So i'm not suprised:-(

**Comment by jlxq0** [comment]
That's sad. :( I suggest closing this issue, because it isn't a simplificator-withings bug. If anyone has any hints for me though, they are still welcome.
